service: ynab-importer

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  stage: production
  memorySize: 128  # MB
  timeout: 20  # seconds, default is 6 seconds

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json

functions:
  sync-transactions:
    handler: handler.sync
    #events:
    #  - schedule:
    #      rate: cron(0 18 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python
